### ISSUE TITLE
URL error in communicating with pinance

### ISSUE THREAD

**Issue by BuddhaSmiles7** [neberej/pinance#3]
Suddenly today Pinance is able to retrieve data or communicate. Following is the code I tried and the error message I get.

from pinance import Pinance
symbol = "AMD"
stock = Pinance(symbol)
stock.get_quotes()
print(stock.quotes_data)

--> 704     for res in getaddrinfo(host, port, 0, SOCK_STREAM):

URLError: <urlopen error [Errno 11001] getaddrinfo failed>

**Comment by chengsu99** [comment]
seems like real-time data is now closed? Do you have any alternatives?

**Comment by neberej** [comment]
@BuddhaSmiles7 @chengsu99 Both Yahoo and Google finance services have been shut down. 

I have written modules to use new sources. Will merge soon!
